from __future__ import annotations
from typing import Protocol, Sequence, Optional, Mapping
from talos_tui.domain.models import Health, MetricsSummary, Peer, Session, VersionInfo, AuditPage

class GatewayPort(Protocol):
    async def get_version(self) -> VersionInfo: ...
    async def get_health(self) -> Health: ...
    async def get_metrics_summary(self) -> MetricsSummary: ...
    async def list_peers(self) -> Sequence[Peer]: ...
    async def list_sessions(self) -> Sequence[Session]: ...

class AuditPort(Protocol):
    async def get_version(self) -> VersionInfo: ...
    async def list_events(self, limit: int, before: Optional[str]) -> AuditPage: ...

class ConfigPort(Protocol):
    def load_config_readonly(self) -> Mapping[str, str]: ...
    def inspect_env_presence(self) -> Mapping[str, bool]: ...

class AuthPort(Protocol):
    def auth_headers(self) -> Mapping[str, str]: ...
